<?php


function psd_cas_login_cas_user_alter(&$cas_user) {
    $cas_name = $cas_user['name'];
    $schcode = null;
    if(isset($cas_user['attributes']['edupersonorgunitdn:gsnunitcode']))
        $schcode =$cas_user['attributes']['edupersonorgunitdn:gsnunitcode'];
 //   $account = user_load_by_name($cas_name);
    $_SESSION['schcode'] = $schcode;
/*
    if (!$account) {
        // No existing user could be found by CAS username.
        $_SESSION['schcode'] = $schcode;
    } else{
        if($account->status==0){
            sch_login_casLogout();
        }
    }
    */
}


function psd_cas_login_cas_attributes_roles_modify(&$user_attributes) {
    //$cas_attributes = $cas_attributes['name'];

      $attribute = "title";
      //drupal_set_message("hello from psd_cas_login_cas_attributes_roles_modify  ATTRIBUTE=".$attribute); //debug jon
      if (!empty($user_attributes[$attribute])) {
        if (!is_array($user_attributes[$attribute])) {
          //$cas_user_roles[] = $user_attributes[$attribute];
            $user_attributes[$attribute]=trim($user_attributes[$attribute]);
        }
        else {  //jon : is array What case is this and how to handle this ?
          //$cas_user_roles = array_merge($cas_user_roles, $user_attributes[$attribute]);
        }
      }
} //end of function psd_cas_login_cas_attributes_roles_modify(&$user_attributes) {

